### ISSUE TITLE
Possibilità di inserire valori inferiori a 1 nelle dimensioni del tratto

### ISSUE THREAD

**Issue by pyarchinit** [mauroalberti/beePen#1]
Salve,
ho "scoperto" che il vostro plugin, è ben più che un sistema di annotazioni. E' fondamentale per il rilievo archiettonico e archeologico. Infatti mi è stato possibile, dopo aver caricato una pianta raster di un mosaico, disegnare a mano libera tutte le tessere in poco tempo e infine "copiare e incollare" le geometrie dentro al mio layer dedicato alle Unità Stratigrafiche archeologiche che sono poligoni, dato che la linea si autochiude.

Sarebbe bello poter però usare delle penne di spessori molto fini e quindi, nella lista a tendina dello spessore, poter avere valori inferiori a 1. 

Se volete posso fare un fork, modificare e rimandarvi la modifica...ma essedo una lista a tendina, credo che facciate prima da designer o da variabile se passate dinamicamente i valori.

Grazie
Luca

**Comment by mauroalberti** [comment]
Ciao,
ho creato una nuova versione, 0.0.9, ancora non nel repository dei plugin di QGIS, che recepisce i tuoi suggerimenti. La puoi scaricare da:
https://github.com/mauroalberti/beePen/releases/tag/v0.0.9

Se la testi e il risultato è positivo posso poi pubblicarla nel repositori di QGIS.
Grazie,
Mauro

**Comment by Beegis** [comment]
Ragazzo,
mi giro un attimo e hai già fatto tutto... ;-)
Questo Luca ha un sacco di idee e propone delle collaborazioni.
Domani provo a sentirlo e vediamo cosa esce fuori.
Ciao

Il domenica 28 febbraio 2016, Mauro Alberti <notifications@github.com> ha
scritto:
> Ciao,
> ho creato una nuova versione, 0.0.9, ancora non nel repository dei plugin
di QGIS, che recepisce i tuoi suggerimenti. La puoi scaricare da:
> https://github.com/mauroalberti/beePen/releases/tag/v0.0.9
>
> Se la testi e il risultato è positivo posso poi pubblicarla nel
repositori di QGIS.
> Grazie,
> Mauro
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/P47OKM6J2Wm8lQNXFbnRv6wa-BoeYW9RzIaPuRKz_LrL0YuVCDpgvtOMPn6am3nd1F8oHboppAdcpHB04tjOOBJV75AqKbQub6IW1dpRB0nfFa9SPK0Ov4gTVcknBWRTN19YJ-lr8nQpGBO3qvx8rU18ZcIfgg=s0-d-e1-ft#https://github.com/notifications/beacon/AK6FMbbwmY0YfWKOw9HI1yIHj2z90D1cks5pou3AgaJpZM4Hkb5Q.gif
>

**Comment by pyarchinit** [comment]
2.8

Si carica tutto,
disegna,
salva,

2.13/14
una volta chiusa la modifica la linea "scompare" perchè nella
categorizzazione non sono più presenti gli stili delle linee

Spero non sia perchè hanno cambiato qualche API

Se si crea un nuovo layer di annotazione, gli si lascia il medesimo nome
del primo per sovrascriverlo si riceve questo errore:

Al massimo si può mettere un try_except per dire all'utente che deve
salvare o con nome diverso o con diverso path.

2016-02-28T14:39:01 1 Traceback (most recent call last):

File "C:/Users/Windows/.qgis2/python/plugins\beePen\beePen_QWidget.py",
line 154, in create_annotation_layer

_, _ = shapefile_create( file_path, geom_type, fields_dict_list, layer_name
= "layer" )

File "C:/Users/Windows/.qgis2/python/plugins\beePen\geosurf\geo_io.py",
line 586, in shapefile_create

raise OGRIOException, 'Unable to save shapefile in provided path'

OGRIOException: Unable to save shapefile in provided path

Per il resto Grandissimo lavoro!!

Grazie mille!

Vi faccio pubblicità su pyarchinit e unaquantum e QGis italia di Facebook
(di cui sono anche l'admin) appena lo mandi fuori!.

Se hai tutorial in rete o simili, segnalameli che li metto su Qgis Italia
di Facebook.

Ciao

Luca

2016-02-28 14:34 GMT+01:00 Beegis notifications@github.com:

> Ragazzo,
> mi giro un attimo e hai già fatto tutto... ;-)
> Questo Luca ha un sacco di idee e propone delle collaborazioni.
> Domani provo a sentirlo e vediamo cosa esce fuori.
> Ciao
> 
> Il domenica 28 febbraio 2016, Mauro Alberti notifications@github.com ha
> scritto:
> 
> > Ciao,
> > ho creato una nuova versione, 0.0.9, ancora non nel repository dei plugin
> > di QGIS, che recepisce i tuoi suggerimenti. La puoi scaricare da:
> > https://github.com/mauroalberti/beePen/releases/tag/v0.0.9
> > 
> > Se la testi e il risultato è positivo posso poi pubblicarla nel
> > repositori di QGIS.
> > Grazie,
> > Mauro
> > 
> > —
> > Reply to this email directly or view it on GitHub.<
> 
> https://ci3.googleusercontent.com/proxy/P47OKM6J2Wm8lQNXFbnRv6wa-BoeYW9RzIaPuRKz_LrL0YuVCDpgvtOMPn6am3nd1F8oHboppAdcpHB04tjOOBJV75AqKbQub6IW1dpRB0nfFa9SPK0Ov4gTVcknBWRTN19YJ-lr8nQpGBO3qvx8rU18ZcIfgg=s0-d-e1-ft#https://github.com/notifications/beacon/AK6FMbbwmY0YfWKOw9HI1yIHj2z90D1cks5pou3AgaJpZM4Hkb5Q.gif
> 
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mauroalberti/beePen/issues/1#issuecomment-189872510.

## 

https://sites.google.com/site/pyarchinit/
http://www.pyarchinit.altervista.org
pyarchinit - progetto per la gestione integrata dei dati di scavo su
piattaforme GIS Free Open Suorce

**Comment by mauroalberti** [comment]
Ciao Luca, provo a testare con le versioni più recenti di QGIS. Io avevo usato 2.12.1, spero che eventuali cambi delle API in 2.13/14 siano limitate...
L'errore della sovrascrittura dovrebbe essere banale da risolvere.

Grazie del testing,
Mauro

**Comment by mauroalberti** [comment]
> 2.13/14
> una volta chiusa la modifica la linea "scompare" perchè nella categorizzazione non sono più presenti gli stili delle linee
> 
> ## Spero non sia perchè hanno cambiato qualche API

Ho provato con la 2.14.0 ma non ho riscontrato problematiche di perdita stile.. o mi son perso qualcosa?

Appena possibile tolgo il baco della sovrascrittura shapefile..

**Comment by Beegis** [comment]
Il 13/03/2016 14:53, Mauro Alberti ha scritto:

> Closed #1 https://github.com/mauroalberti/beePen/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mauroalberti/beePen/issues/1#event-587809960.

Thanks

2 more requests:
1. Width (map units) should starts at 1 instead of 0,01 (then one can 
   choose thinner or thicker lines)
2. As Red Layer plugin does, it could be usefull to have the choiche to 
   insert a label (add text annotation to sketches)

Cheers

## 

_Mauro De Donatis_ - Associate Professor

Università di Urbino "Carlo Bo"

/Dipartimento di Scienze Pure e Applicate/ - DiSPeA

Campus Scientifico "E. Mattei"

61029 - Urbino (Italy)

tel. (+39) 0722-304295
