### ISSUE TITLE
Update for qGIS 3.0?

### ISSUE THREAD

**Issue by Niennas** [mauroalberti/beePen#2]
Hi Mauro,

Is it possible to update this plugin so that it works with qGIS 3.0? I'm not really technical, but I think it has mainly to do with the python version it uses, since 3.0 uses Python 3.6.

Thanks,
Niels

**Comment by mauroalberti** [comment]
Sure, hopefully within a few months..
Mauro

**Comment by Niennas** [comment]
Thank you very much. 
Niels

**Comment by mauroalberti** [comment]
Created version for QGIS 3

**Comment by Niennas** [comment]
Thanks!
